logging:
    level:
        org:
            springframework: info
security:
    jwt:
        expiration-time: ${JWT_EXPIRATIONTIME}
        secret-key: ${JWT_SECRETKEY}
server:
    error:
        include-binding-errors: always
        include-message: always
    port: 8080
spring:
    config:
        import: classpath:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}
        testWhileIdle: true
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
